
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package grammar;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int RBRACK = 11;
  public static final int MOD = 7;
  public static final int ELSE = 16;
  public static final int PLUS = 3;
  public static final int INT = 18;
  public static final int RBRACE = 13;
  public static final int RPAREN = 9;
  public static final int WHILE = 17;
  public static final int SEMI = 2;
  public static final int CUR = 29;
  public static final int LBRACK = 10;
  public static final int RETURN = 19;
  public static final int GREATER = 25;
  public static final int IF = 15;
  public static final int LPAREN = 8;
  public static final int LBRACE = 12;
  public static final int ID = 31;
  public static final int RANDOM = 14;
  public static final int COMMA = 26;
  public static final int NUMBER = 30;
  public static final int EOF = 0;
  public static final int B = 28;
  public static final int DIVIDE = 6;
  public static final int A = 27;
  public static final int GREATEREQ = 24;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int LESSEQ = 23;
  public static final int EQ = 21;
  public static final int EQEQ = 20;
  public static final int LESS = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "RANDOM",
  "IF",
  "ELSE",
  "WHILE",
  "INT",
  "RETURN",
  "EQEQ",
  "EQ",
  "LESS",
  "LESSEQ",
  "GREATEREQ",
  "GREATER",
  "COMMA",
  "A",
  "B",
  "CUR",
  "NUMBER",
  "ID"
  };
}

